import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fixture } from './helpers.ts';
const cli = resolve('src/cli.ts');
test('CLI resumes across processes, emits real contents and blocks missing mandatory context', () => {
    const f = fixture();
    const id = f.task.taskId;
    f.store.close();
    const run = (args: string[], input?: string) => { const r = spawnSync(process.execPath, [cli, ...args, '--db', join(f.root, '.harness/harness.db')], { cwd: f.root, encoding: 'utf8', input, env: { ...process.env, HARNESS_SESSION: 'fixture-session' } }); return { code: r.status, value: JSON.parse(r.stdout) }; };
    assert.equal(run(['resume', '--task', id]).code, 0);
    let r = run(['context', 'get', '--task', id, '--path', 'a.ts']);
    assert.equal(r.value.artifacts[0].inline, 'first\n');
    r = run(['context', 'get', '--task', id, '--path', 'a.ts', '--mandatory', 'missing']);
    assert.equal(r.code, 2);
    assert.equal(r.value.artifacts.length, 0);
    r = run(['host', 'hook'], JSON.stringify({ session_id: 'fixture-session', cwd: f.root }));
    assert.match(r.value.hookSpecificOutput.additionalContext, new RegExp(id));
    r = run(['check', 'run', '--task', id, '--wait', '31', '--authority-ref', 'test', '--', process.execPath, '-e', 'process.exit(0)']);
    assert.equal(r.code, 2);
    assert.match(r.value.error, /wait/);
    r = run(['usage', '--task', id]);
    assert.equal(r.value.usage.inputTokens, null);
});
test('large artifacts persist verified bytes and explicit identity cannot be overwritten', () => {
    const f = fixture();
    const text = 'a'.repeat(70000);
    const a = f.store.putArtifact({ kind: 'snapshot', subject: 'fixture', path: 'large', inline: text, bytes: text.length, provenance: 'observed' });
    assert.equal(a.inline, null);
    assert.equal(f.store.artifactContent(a.artifactId), text);
    assert.throws(() => f.store.putArtifact({ artifactId: a.artifactId, kind: 'snapshot', subject: 'fixture', path: 'other', inline: text, bytes: text.length, provenance: 'observed' }), /collision/);
    f.store.close();
});
test('v4 stores migrate without losing tasks and unknown schemas stay untouched', async () => {
    const { DatabaseSync } = await import('node:sqlite');
    const { SCHEMA } = await import('../src/store/schema.ts');
    const { Store } = await import('../src/store/store.ts');
    const f = fixture();
    f.store.close();
    const path = join(f.root, 'old.db');
    const db = new DatabaseSync(path);
    db.exec(SCHEMA);
    db.prepare("INSERT INTO meta VALUES('schema_version','4')").run();
    db.prepare("INSERT INTO task(task_id,version,outcome,status,created_at) VALUES('old',1,'legacy task','open','2026-09-19')").run();
    db.close();
    const migrated = new Store(path);
    assert.equal(migrated.readTask('old')!.outcome, 'legacy task');
    assert.equal(migrated.readTask('old')!.parentCheckpoint, null);
    migrated.close();
    const unknown = new DatabaseSync(path);
    unknown.prepare("UPDATE meta SET value='99' WHERE key='schema_version'").run();
    unknown.close();
    assert.throws(() => new Store(path), /unsupported schema/);
    const preserved = new DatabaseSync(path);
    assert.equal((preserved.prepare("SELECT value FROM meta WHERE key='schema_version'").get() as {
        value: string;
    }).value, '99');
    preserved.close();
});
test('CLI enforces read and record constraints, exposes attempts, and bounds event output', () => {
    const f = fixture(), db = join(f.root, '.harness/harness.db');
    f.store.reviseTask(f.task.taskId, [{ kind: 'constraint', body: 'deny:read', provenance: 'operator' }, { kind: 'constraint', body: 'deny:record', provenance: 'operator' }]);
    f.store.appendEvent(f.task.taskId, 'large', { payload: 'x'.repeat(100000) });
    f.store.close();
    const run = (args: string[]) => { const r = spawnSync(process.execPath, [cli, ...args, '--db', db, '--task', f.task.taskId, '--session', 'test'], { cwd: f.root, encoding: 'utf8' }); return { code: r.status, value: JSON.parse(r.stdout), text: r.stdout }; };
    assert.equal(run(['context', 'get', '--path', 'a.ts']).code, 2);
    assert.equal(run(['checkpoint', '--summary', 'denied']).code, 2);
    const r = run(['resume']);
    assert.ok(r.value.attempt.attemptId);
    assert.equal(r.value.workspace.withinTaskScope, true);
    assert.ok(run(['events']).text.length < 16000);
    const path = join(f.root, 'usage.json');
    writeFileSync(path, JSON.stringify({ kind: 'provider', source: 'fixture', measurementId: 'one', inputTokens: 5 }));
    assert.equal(run(['usage', 'record', '--file', path]).value.recorded, true);
});
test('schema5 migration adds item provenance without changing old history', async () => {
    const { DatabaseSync } = await import('node:sqlite');
    const { SCHEMA, V5 } = await import('../src/store/schema.ts');
    const { Store } = await import('../src/store/store.ts');
    const f = fixture();
    f.store.close();
    const path = join(f.root, 'v5.db');
    const db = new DatabaseSync(path);
    db.exec(SCHEMA);
    db.exec(V5);
    db.prepare("INSERT INTO meta VALUES('schema_version','5')").run();
    db.prepare("INSERT INTO task(task_id,version,outcome,status,created_at) VALUES('old',1,'retained','open','2026-09-19')").run();
    db.prepare("INSERT INTO task_item VALUES('old',1,0,'handoff','observed','legacy observation',0)").run();
    db.close();
    const s = new Store(path);
    assert.equal(s.readTask('old')!.items[0]!.origin, null);
    assert.equal(s.readTask('old')!.items[0]!.body, 'legacy observation');
    s.close();
});
