import {test} from "node:test";
import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,realpathSync,rmSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {startupGitAdmission,startupGitSnapshot,assertStartupGitSnapshot,assertStartupGitTransition} from "../src/startup-git.ts";
import {commitStartupLock} from "../src/startup-commit.ts";

test("startup Git admission preserves unrelated work and rejects authority overlap and active operations",async()=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),"startup-git-")));
 const git=(...args:string[])=>execFileSync("git",args,{cwd:root,encoding:"utf8",stdio:["ignore","pipe","pipe"]});
 try {
  git("init");git("config","user.name","Fixture");git("config","user.email","fixture@example.invalid");git("config","commit.gpgsign","false");
  mkdirSync(join(root,"config/governance"),{recursive:true});
  writeFileSync(join(root,"config/governance/runtime.lock.yaml"),"{}\n");writeFileSync(join(root,"code.txt"),"base\n");
  git("add",".");git("-c","core.hooksPath=/dev/null","-c","commit.gpgsign=false","commit","-m","fixture");
  writeFileSync(join(root,"code.txt"),"staged\n");git("add","code.txt");writeFileSync(join(root,"code.txt"),"unstaged\n");
  writeFileSync(join(root,"new file.txt"),"new\n");
  const before=git("status","--porcelain=v1"),admission=startupGitAdmission(root);
  assert.deepEqual(admission.changed,["code.txt","new file.txt"]);assert.equal(admission.admission,"preflight-only");
  assert.equal(git("status","--porcelain=v1"),before);
  const snapshot=startupGitSnapshot(root);assertStartupGitSnapshot(snapshot);
  writeFileSync(join(root,"code.txt"),"another unstaged edit\n");
  assert.throws(()=>assertStartupGitSnapshot(snapshot),/reassessment required/);
  writeFileSync(join(root,"code.txt"),"unstaged\n");assertStartupGitSnapshot(snapshot);
  git("add","code.txt");
  assert.throws(()=>assertStartupGitSnapshot(snapshot),/reassessment required/);
  writeFileSync(join(root,"code.txt"),"staged\n");git("add","code.txt");writeFileSync(join(root,"code.txt"),"unstaged\n");
  assertStartupGitSnapshot(snapshot);
  git("config","test.startup","changed");
  assert.throws(()=>assertStartupGitSnapshot(snapshot),/reassessment required/);git("config","--unset","test.startup");
  assertStartupGitSnapshot(snapshot);
  const hook=git("rev-parse","--path-format=absolute","--git-path","hooks/pre-commit").trim();
  writeFileSync(hook,"#!/bin/sh\nexit 0\n",{mode:0o755});
  assert.throws(()=>assertStartupGitSnapshot(snapshot),/reassessment required/);rmSync(hook);
  assertStartupGitSnapshot(snapshot);
  writeFileSync(join(root,"config/governance/profile.yaml"),"changed\n");
  assert.throws(()=>startupGitAdmission(root),/overlap governance/);rmSync(join(root,"config/governance/profile.yaml"));
  const marker=git("rev-parse","--path-format=absolute","--git-path","index.lock").trim();writeFileSync(marker,"");
  assert.throws(()=>startupGitAdmission(root),/active operation/);rmSync(marker);
  assert.throws(()=>startupGitAdmission(root,{...process.env,GIT_INDEX_FILE:"other-index"}),/redirected/);
  const original="{}\n",candidate='{"version":"3.1.0"}\n',lock=join(root,"config/governance/runtime.lock.yaml");
  writeFileSync(lock,candidate);
  assertStartupGitTransition(snapshot,original,candidate);
  assert.throws(()=>assertStartupGitTransition(snapshot,original,"other bytes"),/prepared transition/);
  writeFileSync(join(root,"code.txt"),"parallel edit\n");
  assert.throws(()=>assertStartupGitTransition(snapshot,original,candidate),/work changed/);
  writeFileSync(join(root,"code.txt"),"unstaged\n");
  const commitInput={before:snapshot,original,candidate,version:"3.1.0",directory:join(root,".git/startup-commit"),deadlineMs:10000};
  const committed=await commitStartupLock(commitInput);assert.equal(committed.status,"committed");
  const committedHead=git("rev-parse","HEAD");
  assert.equal((await commitStartupLock(commitInput)).status,"committed");assert.equal(git("rev-parse","HEAD"),committedHead);
  assertStartupGitTransition(snapshot,original,candidate,true);
  assert.equal(git("diff","--cached","--name-only").trim(),"code.txt");
  assert.throws(()=>assertStartupGitTransition(snapshot,original,candidate),/work changed/);
  writeFileSync(hook,"#!/bin/sh\necho invoked >> .git/failed-hook-ran\nexit 1\n",{mode:0o755});
  const secondSnapshot=startupGitSnapshot(root),next='{"version":"3.2.0"}\n';
  writeFileSync(lock,next);
  const failedInput={before:secondSnapshot,original:candidate,candidate:next,version:"3.2.0",directory:join(root,".git/rejected-commit"),deadlineMs:10000};
  assert.equal((await commitStartupLock(failedInput)).status,"recovery-required");
  assert.equal(git("rev-parse","HEAD"),committedHead);
  assert.equal((await commitStartupLock(failedInput)).status,"recovery-required");
  assert.equal(readFileSync(join(root,".git/failed-hook-ran"),"utf8"),"invoked\n");
  git("checkout","--detach");assert.throws(()=>startupGitAdmission(root));
 }finally{rmSync(root,{recursive:true,force:true});}
});
